name: Build all of the things
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Prep env
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-8.0-releases
          sudo apt update
      - name: Bootstap
        run: make bootstrap
      - name: Build
        run: make
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: prototype-schematic.pdf
          path: eda/prototype/schematic.pdf
