name: Build all of the things
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
         sudo add-apt-repository --yes ppa:kicad/kicad-8.0-releases
         sudo apt update
      - run: make bootstrap
      - run: make
